---
title: Year 9 English Assessment 2
---

<body>
  <h2>English Assessment 2 - Adapt an Ancient Text</h2>
  <h3>The Story</h3>
  <h4>Narcissus and Echo (Prequel from Echo’s perspective)</h4>
  <p>It was a beautiful day, and another warm breeze blew across young Echo's face. Her auburn hair blew in the wind as she closed her eyes. She was with her family on a grassy hill, and for many days, she and her family had come to this hill to draft her future, as had been done for the brothers and sisters before her. It wasn't particularly exciting, but she knew that when she reached maturity, she would be deployed by nature. So, she enjoyed the time on the hill with her family.</p>
  <p>At last, after a few hours, it was decided that she would go live in the forest clearing, by the winding river east of the hill. She would spend a few years taking care of nature, and then she would wed a forest spirit she had worked with. She was also briefed on how nature would guide her for the rest of her years, and how she had to listen to nature's calls and purposes for her.</p>
  <p>Echo had the most jovial of times in the forest clearing with the sprites of the forest, after she was deployed. Every morning, the sun would shine its rays on her back, and the birds would sing the sweetest of melodies as she lay on the grass. Then the sprites would work to keep the forest and the river safe for the people who would visit and hunt. From dawn to dusk, she would interact with the forest visitors and with other sprites. At night, she would go to sleep in the soft grass of the forest clearing, to the sound of crickets chirping and the bright glow of the moon.</p>
  <p>5 years had passed, and one day, Jupiter, god of gods, arrived into the forest clearing. His great form was the buzz and chatter for the day, and all the sprites worked extremely hard to make his stay a good one. The sprites would take in turns chatting to him, and some nymphs made poor attempts to flirt and attract attention from the deity. Jupiter told a multitude of stories, where some were about the world's origin and how it was created, and some were about his adventures to different lands across the world, outside of Rome. The forest sprites who participated enjoyed his stories very much, as well as his company.</p>
  <p>Finally, Juno, Jupiter's wife ascended from the heavens to where the Jupiter was. In fright, most of the nymphs left, just leaving some nymphs and male sprites. Like usual, the sprites introduced themselves as the forest caretakers. As Juno settled down with Jupiter, the sprites slowly fled from the clearing, until it was just Echo remaining. Juno quickly realised the situation between the forest sprites and Jupiter, and what the nymphs especially were doing. Angered, Juno announced, "Your tongue. With which you tricked me, now its power shall lose, your voice avail but for the briefest use."</p>
  <p>From then, Echo was unable to speak, except to only repeat the last words of a spoken passage. She roamed the forest as a self-exiled nymph, and never again did she meet the eyes of her old sprite friends. She walked further north, and at last, she reached a clear pool, and a cave, and that was where she decided to settle.</p>
  <p>Around 2 years into her settlement, a young boy of 16 wandered through the forest. The boy had beautiful pale skin, dazzling blue eyes and such glamourous long hair so good that it could be used as a decoration. His fine face and gentle blush was worthy for the most beautiful girl. With this, Echo's heart was fired, and she crept towards the young boy. The closer she crept, the brighter the flame burned, as if the distace between them was like a candle's wick burning. Soon, she felt the full extent of the flame, and she longed for words to come to her again, but nature opposed.</p>
  <p>"Anyone here?" shouted the young boy suddenly. Echo seized the opportunity and shouted "here!" in reply. The youth turned in her direction, and shouted "Com this way!" "This way!" was Echo's reply. There was a pause, and the boy once again shouted, "Why run away?" Echo, having no words she could use, stayed silent and waited for her next opportunity. "Join me here!" came the reply, and ecstatically, Echo repeated the phrase, ran up to the boy and flung her arms around his ivory neck. The boy quickly, retracted, shouting "Keep your arms from me! Be off! I'll die before I yield to you." Dejectedly, Echo answered "I yield to you."</p>
  <p>Even rejected and dismissed, Echo's love for the young man continued to burn bright, and the pain of love showed its effects on her as she retreated to the cave she lives in. For years, she lay on the hard ground, never eating, never sleeping, only mourning the days away for her lost love. Her body slowly dissolves with the tears that she weeps. Soon, the only thing left of her is her voice, and through hills and valleys her voice roams, repeating only the final words of speech.</p>
  <h3>Reflection and Results</h3>
  <h4>Reflection</h4>
  <p>Gosh I'm really not proud of this one. I wrote this the morning of it was due, because I had a whole bunch of things come up and I wasn't allowed to start my assignment until the Tuesday afternoon. I didn't even get to finish my draft since I had to run off to the Chorale rehearsal, and on the Wednesday we got relief'd again, so I couldn't finish the draft. On the Wednesday night I had the concert and my laptop died so I wasn't able to do much of the final copy either. It was around 10:30 when I got back home and did it, so really not feeling good about this as of writing. Not expecting very much either, just hoping I can get a highish B.</p>
  <h4>Results</h4>
  <p>Ok ok I knew I did bad but I didn't think I did THAT bad! I was on the verge of a letter of concern ;-;<br>Anyways, I don't want to talk about it</p>
</body>
